@Library('my-shared-library') _

pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                script {
                    myLibrary.buildApp()
                }
            }
        }
          stage('Create SonarQube Project') {
             steps {
                  script {
                     sonarCreateProject(env.JOB_NAME)
               }
          }
        }

        stage('SonarQube Scan') {
             steps {
                  script {
                    sonarLocalScan()
                }
         }
        }
        
        stage('Deploy') {
            steps {
                script {
                    myLibrary.deployApp()
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    myLibrary.cleanup()
                }
            }
        }
    }
}